# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        # ← bump from v2 → v3
        uses: actions/upload-pages-artifact@v3
        with:
          path: .   # point at your index.html & assets

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
